Admin dashboard v2.1 from revert
tairea/galaxy-maps-v2 pull request #117
Opened 2024-03-04 18:15 UTC by tairea

did a bit of work to create some extra tools for teachers.
on cohort view page, next to students, there is a VIEW button that loads a new students overview dash
![image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/75b43072-a6b6-4581-9563-6e5830f9354e)
![image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/7d01d774-83ed-4257-86e2-d27ee1db6ce4)
there is also an XP point feature
![image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/a02960b4-f660-47b3-8886-30f917c9faa4)
i think there were a few minor bugs that i fixed as i came across them

2024-03-04 19:56 UTC, charsleysa commented
You have conflicts that need resolving.

2024-03-05 16:52 UTC, tairea commented
conflict resolved

2024-03-05 22:48 UTC, charsleysa requested changes

2024-03-05 22:48 UTC, charsleysa commented on src/components/AllStudentsView/StudentDataIteratorAdmin.vue
> +    ...mapState(useRootStore, ["currentCohort", "user", "people"]),
currentCohort doesn't exist, you need to use currentCohortId and load the cohort data

2024-03-05 22:48 UTC, charsleysa commented on src/components/CohortView/CohortGraphs.vue
> +    // this.cohortsCoursesData = await fetchCohortCoursesActivityByCohortId(this.cohort.id);
Remove commented code

2024-03-05 22:48 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard.vue
> +    console.log(
Remove debugging

2024-03-05 22:48 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentCircularProgress.vue
> +import { mapState } from "pinia";
Remove unused import

2024-03-05 22:48 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentCircularProgress.vue
> +    console.log("Activity from circle progress:", this.activity);
Remove debugging

2024-03-05 22:48 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentCircularProgress.vue
> +      console.log(
Remove debugging

2024-03-05 22:48 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentCircularProgress.vue
> +        console.log(
Remove debugging

2024-03-05 22:48 UTC, charsleysa commented on src/components/Dialogs/AssignCohortDialog.vue
> +    ...mapActions(useRootStore, ["bindCourses", "setSnackbar", "getPersonById"]),
Remove unused action

2024-03-05 22:48 UTC, charsleysa commented on src/components/Dialogs/AssignCohortDialog.vue
> +            // console.log(
Remove commented code

2024-03-05 22:48 UTC, charsleysa commented on src/components/Dialogs/StudentEditDialog.vue
> +    if (this.student) {
Avoid this, either have the data loaded in the dialog or have the data passed through props.
Dont reuse the same dialog for different purposes with different permissioning requirements.

2024-03-05 22:48 UTC, charsleysa commented on src/components/GalaxyList/VersionStatus.vue
> +      versionNumber: "0.24.03.01", // [version.year.month.patch]
Use 3 segment versioning not 4 as it's more standard

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/Avatar.vue
> +        await db
Replace with getPersonById ff call

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/Chart.vue
> +          // console.log("bar chart chartData", this.chartData);
Remove commented code

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/Chart.vue
> +          // console.log("chartData watcher for ", this.chartType, ": ", newVal);
Remove commented code

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/ProgressionLineChartStudentCourses.vue
> +    // ...mapState(useRootStore, ["person"]),
Remove commented code

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/RequestForHelpTeacherFrame/RequestForHelpTeacherPanelDense.vue
> +        v-for="(sub, i) in [request]"
For loop not needed

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/SubmissionTeacherFrame.vue
> +      // console.log("old val:", oldVal);
Remove commented code

2024-03-05 22:48 UTC, charsleysa commented on src/components/Reused/LearnerOverviewDashboard.vue
> +      return this.accountType === "teacher";
Where does accountType come from?

2024-03-06 17:39 UTC, tairea commented on functions/src/courseManagement.ts
> +// TODO: add a teachers array to courses so can check if teacher is on that course
do you mean instead of getting submissions/requestsforhelp by course teacher, we get them by cohort teachers?
this make sense, as the ui shows these in cohort view.
the things is they are currently saved as a collection in the courses db.
are you suggestinng we move submissions/requestsforhelp to the cohorts db instead?
or are you suggesting do some kind of get of cohort teachers ids, then get from courses where content/mapped by includes cohort.teachers.id ?
i think the second one is an easier fix.
thanks for the idea.

2024-03-06 17:45 UTC, tairea commented on functions/src/courseManagement.ts
> +export const getStudentSubmissionsByPersonIdForATeacherHttpsEndpoint = runWith({}).https.onCall(
should this filter by teacher id happen here in getStudentSubmissionsByPersonId cloud function or on the results on the client side in fetchStudentSubmissionsByPersonId ?

2024-03-06 20:11 UTC, charsleysa commented on functions/src/courseManagement.ts
> +export const getStudentSubmissionsByPersonIdForATeacherHttpsEndpoint = runWith({}).https.onCall(
Do the filtering server side. TeacherId isn't needed as an input, you can use the authenticated user ID.

2024-03-06 20:19 UTC, charsleysa commented on functions/src/courseManagement.ts
> +// TODO: add a teachers array to courses so can check if teacher is on that course
Get a list of cohorts for the teacher, then get courses for the cohorts, then get submissions / requests for help for those courses. No need to filter on mappedBy or contentBy fields.

2024-03-06 20:20 UTC, charsleysa commented on functions/src/courseManagement.ts
> +    const submissionsPromises = coursesSnapshot.docs.map(async (courseDoc) => {
You can ignore this one, it was a mistake.

2024-03-07 19:33 UTC, tairea commented on functions/src/courseManagement.ts
> +  if (courseCollection.empty) {
true

2024-03-07 19:37 UTC, tairea commented on functions/src/veracityLRS.ts
> +      console.log("Statement:", statement);
there is a bug that i was trying to find with this log, but i couldnt find where its logs to.
couldnt find it in cloud functions logs either?
do you know where i would find this log?

2024-03-07 19:50 UTC, tairea commented on functions/src/veracityLRS.ts
> +        id: "",
where does it break the front end because of task.id?
i think its currently breaking `StudentCircularProgress.vue` because statements topic.id showing as `undefined`.
thats why i was hoping the IF statements below that set newStatement.id eg: `newStatement.id = statement.topic`would work. there was a bug as you pointed out with statement.course.
but yeah, im having trouble fixing this.

2024-03-07 20:07 UTC, tairea commented on src/components/CohortView/StudentDataIterator/StudentCard.vue
> +      this.$emit("updateStudentsWithLastActive", {
kinda still correct as updates students plural as it does update this.students[student].lastActive
mish to change and test.
does it matter? can we let it slide? 😇
refactor if you wish?

2024-03-07 20:23 UTC, tairea commented on src/store/index.ts
> +    async deleteCourseFromPerson(personId: string, courseId: string) {
sorry man not sure how.
getting this error
<img width="682" alt="image" src="https://github.com/tairea/galaxy-maps-v2/assets/37652388/e11c2c96-924c-43a5-8cb5-c643a1b69ebe">
do you mind doing this one?

2024-03-07 20:34 UTC, tairea commented on src/lib/ff.ts
> +  courseId: string,
was changed to match order of params where it is called in `StudentCircularProgress.vue`
looks right to me.
but there is a bug somewhere, not sure what is wrong?

2024-03-07 20:38 UTC, charsleysa commented on src/lib/ff.ts
> +  courseId: string,
Don't change the function definition, change the call site instead

2024-03-07 20:45 UTC, charsleysa commented on functions/src/veracityLRS.ts
> +      console.log("Statement:", statement);
All logs for firebase functions would be available in the cloudfunctions logs. Double check that you have deployed the code changes to firebase otherwise it won't work. If you're still not seeing anything then that code path isn't being executed.

2024-03-07 20:52 UTC, tairea commented on src/components/Dialogs/StudentEditDialog.vue
> +    if (this.student) {
not sure what to do instead?
is it going to be an issue? can we let it slide? 😇

2024-03-07 20:54 UTC, tairea commented on src/components/GalaxyList/VersionStatus.vue
> +      versionNumber: "0.24.03.01", // [version.year.month.patch]
sounds good.

2024-03-07 23:11 UTC, tairea commented on functions/src/courseManagement.ts
> +// TODO: add a teachers array to courses so can check if teacher is on that course
wrote the logic for this in getSubmissionsForTeacherByTeacherIdHttpsEndpoint()` and `getRequestsForTeacherByTeacherIdHttpsEndpoint`
but ill still have to filter by courses and student.
is this better than what i had?

2024-03-07 23:37 UTC, tairea commented on src/lib/ff.ts
> +  courseId: string,
true

2024-03-08 00:11 UTC, charsleysa requested changes

2024-03-08 00:11 UTC, charsleysa commented on src/store/index.ts
> +    async deleteCourseFromPerson(personId: string, courseId: string) {
take a look `assignCourseToStudentHttpsEndpoint`, its essentially the same steps but in reverse

2024-03-08 00:11 UTC, charsleysa commented on src/lib/ff.ts
> +    courseId,
unnecessary change

2024-03-08 00:11 UTC, charsleysa commented on src/components/Reused/Avatar.vue
> +        await fetchPersonByPersonId(this.personId ? this.personId : this.profile.id);
you're not storing the result of the fetch anywhere

2024-03-08 00:11 UTC, charsleysa commented on src/components/Reused/Avatar.vue
> +      } else if (this.personId || this.profile.id) {
the second part of the condition will cause an error. this if statement can never be reached if `this.profile` is not null which means `this.profile.id` will cause an access on undefined error

2024-03-08 00:11 UTC, charsleysa commented on src/components/GalaxyList/VersionStatus.vue
> +      versionNumber: "0.2403.01", // [version.year.month.patch]
revise comment

2024-03-08 00:11 UTC, charsleysa commented on src/components/Dialogs/AssignCohortDialog.vue
> +      await this.bindCourses({ owner: this.person.id });
owner takes a ref not an id

2024-03-18 22:13 UTC, charsleysa commented on functions/src/courseManagement.ts
> +    // submissions = submissions.filter(
will follow up with a fix in a separate PR.

2024-03-18 22:13 UTC, charsleysa commented on functions/src/courseManagement.ts
> +      for (const courseId of cohortCourses) {
will follow up with a fix in a separate PR.

2024-03-18 22:13 UTC, charsleysa commented on functions/src/courseManagement.ts
> +      for (const courseId of cohortCourses) {
will follow up with a fix in a separate PR.

2024-03-18 22:18 UTC, charsleysa approved these changes
LGTM

2024-03-18 22:18 UTC, merged

2024-03-18 22:19 UTC, charsleysa commented on src/store/index.ts
> +            ? db.collection("courses").where("mappedBy.personId", "==", payload.owner)
@tairea will follow up with a fix pr.

2024-03-18 22:28 UTC, tairea commented
u da man