Topic completed & galaxy active hours
tairea/galaxy-maps-v2 pull request #96
Opened 2024-01-11 20:13 UTC by tairea

this PR does two things

1. a UI dialog that congrats the user for completing a system(topic) and option to jump straight to next system(topic) - (this was a request from teacher instead of always having to go back to the galaxy view to progress forward.)
![image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/583f4b1d-d566-48e2-8d21-e8fb37462fd1)

2. calculates the active hours spent on individual galaxies(courses). previously active hours showed total hours on the platform.
3. 
![image](https://github.com/tairea/galaxy-maps-v2/assets/37652388/d551d22e-e9e5-470e-a4e4-7eba9a079b81)

2024-01-11 22:21 UTC, charsleysa requested changes

2024-01-11 22:21 UTC, charsleysa commented on src/components/Dialogs/MissionCompletedDialog.vue
> +import confetti from "canvas-confetti";
Import order

2024-01-11 22:21 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentHours.vue
> +import { fetchCourseByCourseId } from "@/lib/ff";
Import order

2024-01-11 22:21 UTC, charsleysa commented on src/views/SolarSystemView.vue
> +        @emitTopicCompleted="setTopicCompleted"
You've got two different routes for triggering the setTopicCompleted function, one through output emitters and one through the pinia store. You need to pick one route and remove the other.

2024-01-11 22:56 UTC, tairea commented on src/components/Dialogs/MissionCompletedDialog.vue
> +import confetti from "canvas-confetti";
whats the best practice import order? library then functions? so...
does this look better?
```
import confetti from "canvas-confetti";
import { db, functions } from "@/store/firestoreConfig";
import useRootStore from "@/store/index";
import { VueEditor } from "vue2-editor";
import { mapActions, mapState } from "pinia";
import {
  fetchCohortByCohortId,
  fetchCourseByCourseId,
  fetchPersonByPersonId,
  fetchTaskByCourseIdTopicIdTaskId,
  fetchTopicByCourseIdTopicId,
} from "@/lib/ff";
import {
  submitWorkForReviewXAPIStatement,
  reSubmitWorkForReviewXAPIStatement,
  taskMarkedAsCompletedXAPIStatement,
  topicCompletedXAPIStatement,
} from "@/lib/veracityLRS";
import {
  mdiCloudUploadOutline,
  mdiInformationVariant,
  mdiCheck,
  mdiClose,
  mdiCheckboxBlankOutline,
} from "@mdi/js";
```

2024-01-11 23:32 UTC, tairea commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentHours.vue
> +import { fetchCourseByCourseId } from "@/lib/ff";
or is it in the order that its called in the component?

2024-01-11 23:32 UTC, tairea commented on src/views/SolarSystemView.vue
> +        @emitTopicCompleted="setTopicCompleted"
sweet. the emitting didnt work. but store does. so have removed the emitting logic

2024-01-11 23:37 UTC, charsleysa commented on src/components/Dialogs/MissionCompletedDialog.vue
> +import confetti from "canvas-confetti";
Alphabetical

2024-01-11 23:38 UTC, charsleysa commented on src/components/CohortView/StudentDataIterator/StudentCard/StudentHours.vue
> +import { fetchCourseByCourseId } from "@/lib/ff";
Package name alphabetical with @ symbol first

2024-01-11 23:42 UTC, charsleysa commented on src/views/SolarSystemView.vue
> +        @emitTopicCompleted="setTopicCompleted"
You should figure out why emitting wasn't working. It's best to use output emitters for one off events rather than the store as you're not intending to keep the information after the event is processed.

2024-01-12 20:40 UTC, charsleysa approved these changes
LGTM

2024-01-12 20:41 UTC, merged

2024-01-12 20:42 UTC, tairea commented
thanks @charsleysa