start mission button changed
tairea/galaxy-maps-v2 pull request #97
Opened 2024-01-11 23:35 UTC by tairea

just changed the start mission logic, so it starts the next mission straight away instead of the previous start mission dialog ui

2024-01-11 23:48 UTC, charsleysa requested changes

2024-01-11 23:48 UTC, charsleysa commented on src/components/Dialogs/StartMissionDialogV2.vue
> +    ...mapState(useRootStore, ["currentCourseId", "currentTopicId", "person"]),
What's the difference between the topicId prop and the currentTopicId state? If they're the same then prefer the prop. Also, the courseId should use prop too in that case.

2024-01-12 20:11 UTC, tairea commented on src/components/Dialogs/StartMissionDialogV2.vue
> +    ...mapState(useRootStore, ["currentCourseId", "currentTopicId", "person"]),
removed currentTopicId in favour of propped topicId.
attempted to do the same for currentCourseId but this was breaking as touches many different places.
so left currentCourseId as is.

2024-01-12 20:24 UTC, tairea commented
keen to get this one merged into main.
as some the bugs i fixed are bugs in main

2024-01-12 20:39 UTC, charsleysa requested changes

2024-01-12 20:39 UTC, charsleysa commented on src/components/Dialogs/CreateEditDeleteNodeDialog.vue
> +    sortTopics() {
The word sort is being used as a verb, properties should only use nouns and adjectives. Rename to `sortedTopics`

2024-01-12 20:39 UTC, charsleysa commented on src/components/SolarSystemView/MissionsList/MissionsCard.vue
> +              :courseId="courseId"
Dialog has no courseId prop

2024-01-12 20:52 UTC, merged

2024-01-12 20:52 UTC, tairea commented
thanks @charsleysa. u da man